name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install
        run: npm ci

      - name: Create Environment Variables
        run: |
          echo "export const environment = {production: true, API_BASE_URL: '${{ secrets.API_BASE_URL }}'};" > src/environments/environment.prod.ts

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx ng deploy --repo=https://github.com/${{ github.repository }}.git --base-href=/portfolio/ --name=${{ github.actor }} --email=${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
